services:
  frontend:
    build: 
      context: ./frontend
    container_name: frontendFile
    ports:
      - "5173:5173"
    networks:
      - blog
  backend:
    build: 
      context: ./backend
    container_name: backendFile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - blog
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - blog

networks:
  blog:
    driver: bridge